### Test passing data and secrets from caller to reusable workflow

name: Test reusing a workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Message for push to Pantheon\nDefaults to last commit message"
        type: string
        required: false
        default: ''

jobs:
  call-workflow:
    uses: SU-UComm/github-workflows/.github/workflows/reusable-test.yml@master
    with:
      site: stanford-news # the site on Pantheon we're deploying to, e.g. stanford-news
      component_folder: wp-content/themes/news # where in Pantheon's repo this code should go, e.g. wp-content/themes/news
      message: ${{ github.event.inputs.message }} # optional message when manually running workflow
    secrets: inherit
